# -*- coding: utf-8 -*-
"""Banco de situaciones de 'Fuera de la Media'.

Cada categoría define cómo se pregunta y qué significan los extremos de la
escala. Los items de la categoría 'grupo' usan {nombre}, que se reemplaza por
un jugador al azar al momento de sortear la carta.
"""

CATEGORIAS = {
    "red_flags": {
        "nombre": "🚩 Es un 10, pero...",
        "pregunta": "¿Qué tan grave es esta red flag?",
        "label_min": "Detalle menor, sigue siendo un 10",
        "label_max": "Red flag gigante, corre",
        "items": [
            "Es un 10, pero se come los mocos.",
            "Es un 10, pero no se lava las manos después de ir al baño.",
            "Es un 10, pero le escribe a su ex 'solo como amigos' todos los días.",
            "Es un 10, pero tiene 35 años y su mamá le hace la cama.",
            "Es un 10, pero aplaude cuando aterriza el avión.",
            "Es un 10, pero dice 'jajaja' en voz alta en vez de reírse.",
            "Es un 10, pero usa calcetines con sandalias.",
            "Es un 10, pero dice que no le gusta la música. Ninguna.",
            "Es un 10, pero mastica con la boca abierta.",
            "Es un 10, pero cree que la Tierra es plana.",
            "Es un 10, pero nunca deja propina.",
            "Es un 10, pero le pone ketchup a todo, incluso a la pizza.",
            "Es un 10, pero tiene una foto enmarcada de sí mismo en su pieza.",
            "Es un 10, pero responde los mensajes una semana después.",
            "Es un 10, pero anda metido en una pirámide financiera y quiere reclutarte.",
            "Es un 10, pero habla de sí mismo en tercera persona.",
            "Es un 10, pero no ha leído un libro en su vida y lo dice con orgullo.",
            "Es un 10, pero deja la ropa sucia en el suelo 'para después'.",
            "Es un 10, pero ha visto su serie favorita 14 veces y se niega a ver otra.",
            "Es un 10, pero pelea con desconocidos en internet todos los días.",
            "Es un 10, pero toma todas sus decisiones según el horóscopo.",
            "Es un 10, pero nunca anda con plata y 'te transfiere después' (nunca transfiere).",
            "Es un 10, pero le habla al perro con voz de guagua… en público… fuerte.",
            "Es un 10, pero se ríe de sus propios chistes antes de contarlos.",
            "Es un 10, pero usa lentes de sol dentro de lugares cerrados.",
            "Es un 10, pero dice 'literal' literalmente cada tres palabras.",
            "Es un 10, pero se pone a cantar en la mesa cuando suena su canción.",
            "Es un 10, pero revisa tu teléfono 'de cariño'.",
            "Es un 10, pero no sabe andar en bicicleta y no quiere aprender.",
            "Es un 10, pero colecciona fotos con famosos que claramente no lo recuerdan.",
            "Es un 10, pero se cree sommelier por haber ido a una viña una vez.",
            "Es un 10, pero pide la comida más cara cuando invitas tú.",
            "Es un 10, pero dice 'yo soy súper directo' antes de decir algo pesado.",
            "Es un 10, pero se echa medio frasco de perfume, se siente a una cuadra.",
            "Es un 10, pero le pone azúcar al vino tinto.",
            "Es un 10, pero cuenta el final de las películas 'sin querer'.",
            "Es un 10, pero llega tarde a todo, siempre, sin excepción.",
            "Es un 10, pero dice que la kinesiología es lo mismo que la brujería.",
            "Es un 10, pero su cama es un colchón en el suelo 'por minimalismo'.",
            "Es un 10, pero tiene guardados los contactos de sus ex con corazones.",
            "Es un 10, pero graba audios de 6 minutos para decir una cosa.",
            "Es un 10, pero se lava los dientes una vez al día 'porque es suficiente'.",
            "Es un 10, pero pide para llevar en los matrimonios.",
            "Es un 10, pero no sabe hacer ni un huevo frito.",
            "Es un 10, pero le cae mal tu mejor amigo/a 'por vibras'.",
            "Es un 10, pero usa la toalla mojada y la deja sobre la cama.",
            "Es un 10, pero pone reggaetón a las 8 de la mañana un domingo.",
            "Es un 10, pero dice 'no soy celoso/a' y te pregunta quién te escribió.",
            "Es un 10, pero se saca los zapatos en el avión.",
            "Es un 10, pero considera que el pan con palta es 'cocinar'.",
            "Es un 10, pero interrumpe todas tus historias con una historia suya mejor.",
            "Es un 10, pero anda con la billetera de velcro desde octavo básico.",
            "Es un 10, pero se sabe de memoria las patentes de los autos de sus ex.",
            "Es un 10, pero cree que los signos zodiacales son incompatibles y por eso terminó una relación.",
            "Es un 10, pero mastica hielo en el cine.",
            "Es un 10, pero dice 'te lo dije' cada vez que puede.",
            "Es un 10, pero jamás ha pedido perdón, por nada.",
            "Es un 10, pero se pesa todos los días y te informa el resultado.",
            "Es un 10, pero duerme con 14 peluches y todos tienen nombre.",
            "Es un 10, pero le manda memes a tu mamá.",
            "Es un 10, pero se cree influencer con 200 seguidores.",
            "Es un 10, pero paga todo en monedas.",
            "Es un 10, pero opina de fútbol sin haber visto un partido completo.",
            "Es un 10, pero usa audífonos mientras le hablas 'pero te escucho'.",
            "Es un 10, pero comenta las películas en el cine, en voz alta.",
            "Es un 10, pero se toma tu bebida 'para probarla' y se la termina.",
            "Es un 10, pero cuenta plata ajena: sabe cuánto gana todo el mundo.",
            "Es un 10, pero tiene la foto de perfil con su ex recortada (se le ve el brazo).",
            "Es un 10, pero llora con los comerciales pero no en tu cumpleaños.",
            "Es un 10, pero dobla la pizza como sándwich para comérsela más rápido.",
            "Es un 10, pero te corrige la ortografía en los chats.",
            "Es un 10, pero dice 'yo a esa edad ya trabajaba' y tiene 26.",
            "Es un 10, pero se estaciona ocupando dos espacios.",
            "Es un 10, pero pide agua de la llave en las citas para ahorrar.",
            "Es un 10, pero tiene un podcast y te obliga a escucharlo.",
            "Es un 10, pero saluda a los meseros chasqueando los dedos.",
            "Es un 10, pero nunca ha ido al doctor 'porque el cuerpo se cura solo'.",
            "Es un 10, pero se ducha con calcetines.",
            "Es un 10, pero le pone sal a la comida antes de probarla.",
            "Es un 10, pero cree que las siestas son de flojos y te despierta.",
            "Es un 10, pero repite los chistes que le funcionaron en otras juntas.",
            "Es un 10, pero anda diciendo que fue seleccionado nacional 'pero se lesionó'.",
            "Es un 10, pero tiene el teléfono con la pantalla rota hace 3 años.",
            "Es un 10, pero pide sushi y lo come con la mano… el arroz queda en todas partes.",
            "Es un 10, pero su plan ideal de viernes es ordenar el clóset.",
            "Es un 10, pero te presenta como 'un amigo/una amiga' después de 8 meses.",
            "Es un 10, pero juega con el pan y deja miguitas por toda la mesa.",
            "Es un 10, pero usa frases de coach: 'el universo conspira', 'todo pasa por algo'.",
            "Es un 10, pero se sabe los diálogos de Shrek y los recita completos.",
            "Es un 10, pero apuesta en todo: partidos, carreras, cuánto demora el metro.",
            "Es un 10, pero nunca cierra los cajones ni las puertas del mueble.",
            "Es un 10, pero le achaca todo a su Mercurio retrógrado.",
            "Es un 10, pero eructa y dice 'buen provecho'.",
            "Es un 10, pero silba cuando está feliz. Todo el día. Todos los días.",
            "Es un 10, pero tiene una lista de Excel con todas sus citas anteriores.",
            "Es un 10, pero contesta el teléfono en el cine y dice 'estoy en el cine'.",
            "Es un 10, pero guarda los regalos que le hacen para regalárselos a otra gente.",
            "Es un 10, pero se emociona más con su auto que contigo.",
            "Es un 10, pero dice 'mi mamá lo hace mejor' en cada comida.",
            "Es un 10, pero está convencido de que puede aterrizar un avión si la tripulación falla.",
        ],
    },
    "opiniones": {
        "nombre": "🌶️ Opiniones tibias",
        "pregunta": "¿Qué tan de acuerdo estás?",
        "label_min": "En total desacuerdo",
        "label_max": "Totalmente de acuerdo",
        "items": [
            "La piña en la pizza es completamente válida.",
            "Llegar 15 minutos tarde no es llegar tarde.",
            "El desayuno está sobrevalorado.",
            "Es mejor ducharse en la noche que en la mañana.",
            "Los audios de WhatsApp de más de un minuto deberían estar prohibidos.",
            "El completo es mejor que el hot dog gringo.",
            "Ver la película sin subtítulos es la única forma correcta.",
            "Trabajar desde la casa es mejor que ir a la oficina, siempre.",
            "El asado lo arruina el que lleva ensaladas gourmet.",
            "Bañarse todos los días es innecesario.",
            "Los cumpleaños dejan de importar después de los 25.",
            "La palta merece su precio.",
            "Dormir con calcetines es de psicópatas.",
            "El mejor pan es la marraqueta, fin de la discusión.",
            "Las películas de superhéroes son todas iguales.",
            "Está bien pedir sushi con palta y queso crema aunque los puristas lloren.",
            "Los stickers reemplazaron completamente la necesidad de escribir.",
            "Salir del cine si la película es mala es un derecho.",
            "El café de máquina no es café.",
            "Un matrimonio sin barra libre es media estafa.",
            "Los gatos son mejores que los perros.",
            "La cerveza sin alcohol tiene sentido.",
            "El ketchup en los tallarines es un crimen imperdonable.",
            "Diciembre empieza el 1 de noviembre.",
            "La música de ahora es peor que la de antes.",
            "Está bien llorar viendo películas de Pixar a cualquier edad.",
            "Los lunes deberían empezar a las 12 del día.",
            "El vino en caja no es tan malo como dicen.",
            "Hacerse la cama todos los días es una pérdida de tiempo.",
            "Los niños en los aviones deberían viajar en una sección aparte.",
            "Las teleseries turcas son mejores que las series gringas.",
            "Prestar plata a amigos siempre termina mal.",
            "La mayonesa casera está sobrevalorada.",
            "El fútbol es aburrido si no juega tu equipo.",
            "Las despedidas en el aeropuerto son puro show.",
            "Mandar mensajes de voz para responder un 'ok' es una falta de respeto.",
            "El pebre es la mejor contribución de Chile a la humanidad.",
            "Las fiestas de Año Nuevo están sobrevaloradas y siempre decepcionan.",
            "Es mejor el frío que el calor: del frío te puedes abrigar.",
            "La gente que corre maratones necesita hablar de otra cosa.",
            "El brunch es solo un desayuno caro y tarde.",
            "Los libros de autoayuda no ayudan a nadie.",
            "Los emojis en correos de trabajo son perfectamente aceptables.",
            "Las palomitas dulces son mejores que las saladas.",
            "Todo evento social debería terminar máximo a la 1 AM.",
            "El camping es pasarlo mal voluntariamente y pagar por ello.",
            "La tortilla de papas lleva cebolla, sí o sí.",
            "Los cuadernos nuevos se compran solo por el olor.",
            "Un buen mote con huesillo le gana a cualquier postre gourmet.",
            "Los tatuajes de infinito deberían pagar impuesto.",
            "El reggaetón antiguo es objetivamente mejor que el actual.",
            "Las llamadas telefónicas sin aviso previo son una agresión.",
            "La gente que dice 'yo no veo tele' ve más pantalla que todos.",
            "Los jeans apretados son un instrumento de tortura socialmente aceptado.",
            "El helado en invierno hace todo el sentido del mundo.",
            "Las plantas son mascotas para gente ocupada.",
            "Es mejor regalar plata que regalar un regalo malo.",
            "Los grupos de WhatsApp familiares deberían poder silenciarse para siempre.",
            "La sopaipilla sin pebre es solo pan frito triste.",
            "Los influencers de viajes hacen que odies tus vacaciones.",
            "Las bodas de destino son un abuso contra los invitados.",
            "El karaoke solo es divertido para el que canta.",
            "Es perfectamente aceptable irse de una fiesta sin despedirse.",
            "El té le gana al café en todas las categorías.",
            "Los perros pequeños son más agresivos que los grandes.",
            "Ver realities es un placer culpable que nadie debería juzgar.",
            "El terremoto (el trago) es la peor idea de la historia de Chile.",
            "Las empanadas de horno le ganan a las fritas.",
            "La primera fila del cine debería ser gratis.",
            "Hablar del clima es la forma más honesta de decir 'no sé qué decirte'.",
            "Los cursos online que compraste jamás los vas a terminar.",
            "La gente puntual sufre más que la gente atrasada.",
            "El aire acondicionado en las oficinas está calibrado para pingüinos.",
            "Un viernes en casa le gana a cualquier carrete.",
            "Los que escuchan música sin audífonos en el transporte público merecen multa.",
            "Las fotos de comida en Instagram no le importan a nadie.",
            "Repetir ropa en eventos distintos es completamente normal.",
            "Las cábalas de Año Nuevo funcionan (las lentejas, las maletas, todo).",
            "El chocolate blanco no es chocolate.",
            "Las reuniones que pudieron ser un correo son la mayoría.",
            "Bailar en los matrimonios debería ser opcional, no una obligación social.",
            "Los asientos del medio en el avión deberían costar la mitad.",
            "La once es mejor que la cena.",
            "Guardar la ropa 'para una ocasión especial' es un error: la ocasión nunca llega.",
            "Los spoilers después de una semana del estreno son culpa tuya.",
            "Un asado que empieza 'a las 2' en realidad empieza a las 5.",
            "La gente que madruga voluntariamente esconde algo.",
            "El pan de molde con los bordes cortados es para la realeza.",
            "Las notas de voz se escuchan en velocidad 2x o no se escuchan.",
            "Los restoranes con música fuerte no quieren que converses: quieren que consumas.",
            "El picoteo es mejor que el plato de fondo.",
            "Todos fingimos entender de vinos.",
            "Los domingos en la tarde tienen una tristeza científicamente comprobable.",
            "Las cadenas de 'reenvía esto a 10 personas' arruinaron una generación.",
            "El orden alfabético en las listas de curso marcó tu personalidad.",
            "Un abrazo largo es más incómodo que un apretón de manos.",
            "La lista de reproducción del dueño del auto es ley.",
            "Ir al gimnasio en enero es un ritual de autoengaño colectivo.",
            "La michelada es una forma de arruinar dos cosas buenas a la vez.",
            "Los restoranes deberían prohibir las velitas de cumpleaños con canto incluido.",
        ],
    },
    "gravedad": {
        "nombre": "⚖️ ¿Qué tan grave?",
        "pregunta": "¿Qué tan grave es esto?",
        "label_min": "Nada grave",
        "label_max": "Imperdonable",
        "items": [
            "Tu pareja le da like a todas las fotos de su ex.",
            "Un amigo te pide plata prestada y nunca más lo menciona.",
            "Alguien se come tu comida etiquetada del refrigerador de la oficina.",
            "Tu mejor amigo/a le cuenta tu secreto a su pareja 'porque se cuentan todo'.",
            "Alguien llega a una junta con un amigo que nadie invitó.",
            "Tu pareja revisa tu teléfono mientras duermes.",
            "Un amigo se pone a pololear y desaparece 6 meses.",
            "Alguien cuenta el final de la serie que estabas viendo.",
            "Te enteras por Instagram de que tus amigos se juntaron sin ti.",
            "Tu compañero de trabajo se atribuye una idea tuya frente al jefe.",
            "Alguien devuelve el auto que le prestaste con el estanque vacío.",
            "Tu pareja se ve los capítulos de la serie compartida sin ti.",
            "Un amigo te deja en visto pero sube historias.",
            "Alguien usa tu cepillo de dientes 'por emergencia'.",
            "Tu suegra opina de cómo deberías criar a tus hijos... cada vez que te ve.",
            "Un amigo se copia tu disfraz después de preguntarte de qué ibas a ir.",
            "Alguien paga con la tarjeta del grupo y se queda con el vuelto.",
            "Tu pareja olvida su aniversario por segundo año consecutivo.",
            "Un amigo te vende algo más caro de lo que le costó, y lo descubres.",
            "Alguien se ríe de un chiste tuyo y después lo cuenta como propio.",
            "Tu compañero de casa se come lo último que quedaba sin preguntar.",
            "Alguien te saluda de cumpleaños un día tarde con 'se me pasó jaja'.",
            "Tu pareja coquetea 'de amistoso' con el/la barista.",
            "Un amigo cancela el plan una hora antes con una excusa obviamente falsa.",
            "Alguien deja el rollo de papel higiénico vacío y no lo repone.",
            "Te copian en un correo donde hablan mal de otro colega.",
            "Tu amigo maneja después de tomarse 'solo dos'.",
            "Alguien publica una foto donde tú sales horrible pero él/ella sale bien.",
            "Tu pareja le pone 'me encanta' a las fotos de gente que no conoce.",
            "Un familiar comenta tu peso en el almuerzo familiar.",
            "Alguien masca chicle con la boca abierta al lado tuyo en el metro.",
            "Tu jefe te escribe un sábado a las 9 PM 'para el lunes a primera hora'.",
            "Un amigo te pide que le hagas el currículum y ni te da las gracias.",
            "Alguien se estaciona en el espacio para personas con discapacidad 'solo 5 minutos'.",
            "Tu pareja dice 'estoy bien' y claramente no está bien, y te lo cobra después.",
            "Un amigo pone su canción en la mitad de la tuya en el karaoke.",
            "Alguien se cuela en la fila del supermercado 'porque lleva poquito'.",
            "Tu hermano/a te saca ropa sin permiso y la devuelve manchada.",
            "Un amigo te etiqueta en un meme ofensivo frente a toda tu familia.",
            "Alguien te corrige en público en vez de decírtelo en privado.",
            "Tu pareja invita a sus amigos a tu plan romántico 'para que sea más entretenido'.",
            "Un colega calienta pescado en el microondas de la oficina.",
            "Alguien te pide un favor gigante y te dice 'pero si no puedes, no importa'.",
            "Tu amigo le echa la culpa al perro (no hay perro).",
            "Alguien pide 'una papita' y se come la mitad de las tuyas.",
            "Tu pareja usa tu shampoo caro para lavar al perro.",
            "Un amigo te presenta con el nombre equivocado y no lo corrige.",
            "Alguien reenvía tu mensaje privado a otro chat.",
            "Tu compañero de asiento se queda dormido en tu hombro en el avión.",
            "Un amigo se declara fan de una banda que descubrió por ti, y no te da crédito.",
            "Alguien llega con las manos vacías al asado, otra vez.",
            "Tu pareja te compara con su ex ('él/ella sí sabía cocinar').",
            "Un amigo te pide ser su padrino/madrina de bodas y luego te degrada a invitado.",
            "Alguien pone los pies en el asiento de enfrente en el cine.",
            "Tu roommate hace fiesta un martes sin avisarte.",
            "Un familiar te pregunta '¿y cuándo el pololeo/matrimonio/hijo?' en cada evento.",
            "Alguien habla por teléfono en altavoz en la sala de espera.",
            "Tu amigo te deja hablando solo para irse a saludar a alguien 'más importante'.",
            "Alguien te dice 'te ves cansado/a' en vez de hola.",
            "Tu pareja se duerme en la película que tú elegiste, pero te obliga a ver las suyas.",
            "Un amigo publica la foto del carrete donde claramente dijiste 'esa no'.",
            "Alguien te devuelve el táper sin lavar. O peor: no te lo devuelve.",
            "Tu colega se lleva el crédito del trabajo grupal en la presentación.",
            "Un amigo organiza su cumpleaños en el restorán más caro y divide la cuenta en partes iguales.",
            "Alguien deja 47 platos 'remojando' desde ayer.",
            "Tu pareja mira el teléfono mientras le cuentas algo importante.",
            "Un amigo te dice que tu polola/o 'no es para tanto'.",
            "Alguien se prueba tu ropa nueva antes que tú.",
            "Tu vecino escucha música fuerte un domingo a las 8 AM.",
            "Un amigo te 'presta' su Netflix y luego te cambia la contraseña sin avisar.",
            "Alguien se lleva el mejor pedazo del asado sin ofrecer.",
            "Tu suegro/a llega de visita 'un ratito' y se queda todo el fin de semana.",
            "Un amigo te pregunta cuánto ganas delante de todos.",
            "Alguien te hace spoiler del partido que grabaste para ver después.",
            "Tu pareja cuenta en la junta esa historia tuya que era secreta.",
            "Un desconocido reclina el asiento del avión hasta tu nariz durante toda la comida.",
            "Alguien te pide consejo, no lo sigue, le va mal y te echa la culpa.",
            "Tu amigo llega al cumpleaños, come, y se va antes de cantar el feliz cumpleaños.",
            "Alguien toca el timbre de tu casa sin avisar 'porque andaba cerca'.",
            "Tu compañero de gimnasio no limpia la máquina después de usarla.",
            "Un amigo te debe plata y sube fotos de sus vacaciones.",
            "Alguien critica tu forma de estacionar mientras tú estacionas.",
            "Tu pareja le cuenta a su mamá cada pelea que tienen.",
            "Un amigo se queda con el cambio de la colecta del regalo grupal.",
            "Alguien pide silencio en tu propia casa para escuchar su llamada.",
            "Tu colega renuncia y te deja todos sus pendientes sin avisar.",
            "Un amigo usa tu historia vergonzosa como su chiste estrella en cada junta.",
            "Alguien te 'corrige' la forma de comer sushi en pleno restorán.",
            "Tu pareja acepta planes por los dos sin consultarte.",
            "Un familiar regalón abre los regalos de los demás 'para ayudar'.",
            "Alguien deja la puerta del microondas abierta con los segundos sin borrar.",
            "Tu amigo cuenta cuánto costó el regalo que te hizo.",
            "Alguien se ríe en la parte triste de la película.",
            "Tu roommate adopta un gato sin preguntar. Eres alérgico.",
            "Un amigo te dice 'yo te lo iba a regalar igual' cuando te lo compras tú.",
            "Alguien responde 'jaja' a un mensaje donde le contaste algo importante.",
            "Tu pareja borra el capítulo que tenías grabado para grabar su reality.",
            "Un amigo llega atrasado y encima critica el lugar que elegiste.",
            "Alguien te pide que le cuides al perro 'un fin de semana' y vuelve en dos semanas.",
            "Tu amigo te invita a su matrimonio... solo a la ceremonia, no a la fiesta.",
        ],
    },
    "grupo": {
        "nombre": "👥 Del grupo",
        "pregunta": "¿Qué tan probable es?",
        "label_min": "Imposible",
        "label_max": "100% ya pasó",
        "items": [
            "¿Qué tan probable es que {nombre} llegue tarde a su propio matrimonio?",
            "¿Qué tan probable es que {nombre} se haga famoso/a por un video vergonzoso?",
            "¿Qué tan probable es que {nombre} termine viviendo en otro país?",
            "¿Qué tan probable es que {nombre} olvide el cumpleaños de su mejor amigo/a?",
            "¿Qué tan probable es que {nombre} se gaste el sueldo completo en algo inútil?",
            "¿Qué tan probable es que {nombre} sobreviva a un apocalipsis zombie?",
            "¿Qué tan probable es que {nombre} llore viendo una película de Disney?",
            "¿Qué tan probable es que {nombre} se pierda en su propia ciudad?",
            "¿Qué tan probable es que {nombre} le hable a un famoso como si lo conociera?",
            "¿Qué tan probable es que {nombre} termine trabajando en algo que no estudió?",
            "¿Qué tan probable es que {nombre} adopte un tercer perro/gato sin planearlo?",
            "¿Qué tan probable es que {nombre} se duerma en una fiesta antes de medianoche?",
            "¿Qué tan probable es que {nombre} mande un mensaje al chat equivocado?",
            "¿Qué tan probable es que {nombre} gane una discusión solo por insistencia?",
            "¿Qué tan probable es que {nombre} se tatúe algo de lo que se arrepienta?",
            "¿Qué tan probable es que {nombre} deje a todos plantados por quedarse dormido/a?",
            "¿Qué tan probable es que {nombre} se haga vegano/a por un documental?",
            "¿Qué tan probable es que {nombre} conteste el teléfono en el cine?",
            "¿Qué tan probable es que {nombre} vuelva con su ex?",
            "¿Qué tan probable es que {nombre} se compre algo carísimo 'porque estaba en oferta'?",
            "¿Qué tan probable es que {nombre} termine cantando en el karaoke sin que se lo pidan?",
            "¿Qué tan probable es que {nombre} sepa la vida completa de los vecinos?",
            "¿Qué tan probable es que {nombre} se ofenda por este juego?",
            "¿Qué tan probable es que {nombre} tenga más de 40 pestañas abiertas ahora mismo?",
            "¿Qué tan probable es que {nombre} le crea a un horóscopo que le conviene?",
            "¿Qué tan probable es que {nombre} se pierda el vuelo por estar en el duty free?",
            "¿Qué tan probable es que {nombre} discuta con un GPS?",
            "¿Qué tan probable es que {nombre} se coma algo que se le cayó al suelo?",
            "¿Qué tan probable es que {nombre} stalkee al ex de su pareja hasta el año 2014?",
            "¿Qué tan probable es que {nombre} diga 'yo organizo' y no organice nada?",
            "¿Qué tan probable es que {nombre} se emocione hablando de un tema que nadie preguntó?",
            "¿Qué tan probable es que {nombre} tenga un negocio propio antes de los 40?",
            "¿Qué tan probable es que {nombre} se cambie de look después de una ruptura?",
            "¿Qué tan probable es que {nombre} le ponga nombre a su auto?",
            "¿Qué tan probable es que {nombre} llegue con alguien 'sorpresa' a la próxima junta?",
            "¿Qué tan probable es que {nombre} sea el primero/a en irse de esta junta?",
            "¿Qué tan probable es que {nombre} sea el último/a en irse de esta junta?",
            "¿Qué tan probable es que {nombre} haya practicado una conversación en la ducha?",
            "¿Qué tan probable es que {nombre} gane un reality de convivencia?",
            "¿Qué tan probable es que {nombre} sea eliminado/a primero de un reality de convivencia?",
            "¿Qué tan probable es que {nombre} se ría en un funeral por nervios?",
            "¿Qué tan probable es que {nombre} tenga comida vencida en su despensa ahora?",
            "¿Qué tan probable es que {nombre} responda 'voy llegando' desde su casa?",
            "¿Qué tan probable es que {nombre} se inscriba en el gimnasio y vaya dos veces?",
            "¿Qué tan probable es que {nombre} cuente una película entera si se lo permiten?",
            "¿Qué tan probable es que {nombre} se enamore en vacaciones?",
            "¿Qué tan probable es que {nombre} haga una escena en un restorán por un plato mal hecho?",
            "¿Qué tan probable es que {nombre} sepa cambiar una rueda de auto?",
            "¿Qué tan probable es que {nombre} haya buscado su propio nombre en Google esta semana?",
            "¿Qué tan probable es que {nombre} termine de profesor/a de yoga en Bali?",
            "¿Qué tan probable es que {nombre} use la misma contraseña para todo?",
            "¿Qué tan probable es que {nombre} llore en su propio discurso de matrimonio?",
            "¿Qué tan probable es que {nombre} se compre criptomonedas por un consejo de TikTok?",
            "¿Qué tan probable es que {nombre} devuelva un libro prestado?",
            "¿Qué tan probable es que {nombre} tenga un playlist secreto de música vergonzosa?",
            "¿Qué tan probable es que {nombre} hable con las plantas?",
            "¿Qué tan probable es que {nombre} gane una competencia de comer completos?",
            "¿Qué tan probable es que {nombre} se meta al mar en pleno invierno por una apuesta?",
            "¿Qué tan probable es que {nombre} conozca al amor de su vida en una app?",
            "¿Qué tan probable es que {nombre} sea la razón de una nueva regla en su trabajo?",
            "¿Qué tan probable es que {nombre} salga en las noticias (por algo bueno)?",
            "¿Qué tan probable es que {nombre} salga en las noticias (por algo ridículo)?",
            "¿Qué tan probable es que {nombre} tenga guardado un mensaje sin enviar a su ex?",
            "¿Qué tan probable es que {nombre} se sepa el nombre de todos los perros del barrio y de ningún vecino?",
            "¿Qué tan probable es que {nombre} pida 'lo de siempre' y el mesero sepa qué es?",
            "¿Qué tan probable es que {nombre} haya llorado con un comercial?",
            "¿Qué tan probable es que {nombre} apueste dinero en este mismo juego?",
            "¿Qué tan probable es que {nombre} diga 'última y nos vamos' tres veces esta noche?",
            "¿Qué tan probable es que {nombre} tenga un plan de emergencia para el fin del mundo?",
            "¿Qué tan probable es que {nombre} se cambie de religión por amor?",
            "¿Qué tan probable es que {nombre} sea el/la favorito/a de todas las mamás del grupo?",
            "¿Qué tan probable es que {nombre} haga dieta el lunes y la rompa el martes?",
            "¿Qué tan probable es que {nombre} se quede dormido/a en esta misma junta?",
            "¿Qué tan probable es que {nombre} conteste un mail de trabajo en la playa?",
            "¿Qué tan probable es que {nombre} se pelee con el árbitro en un partido de niños?",
            "¿Qué tan probable es que {nombre} tenga más fotos de su mascota que de su familia?",
            "¿Qué tan probable es que {nombre} improvise un discurso y le salga increíble?",
            "¿Qué tan probable es que {nombre} se compre algo por un influencer?",
            "¿Qué tan probable es que {nombre} haya fingido saber de vinos alguna vez?",
            "¿Qué tan probable es que {nombre} sobreviva una semana sin celular?",
            "¿Qué tan probable es que {nombre} le caiga bien a la suegra al primer intento?",
            "¿Qué tan probable es que {nombre} termine organizando el viaje grupal que nadie más organiza?",
            "¿Qué tan probable es que {nombre} arruine la sorpresa de un regalo por no aguantarse?",
            "¿Qué tan probable es que {nombre} se sepa todas las canciones de una teleserie antigua?",
            "¿Qué tan probable es que {nombre} pierda las llaves esta semana?",
            "¿Qué tan probable es que {nombre} se haga amigo/a del taxista y termine con su número?",
            "¿Qué tan probable es que {nombre} diga 'yo no tomo hoy' y sea el/la primera en pedir otra?",
            "¿Qué tan probable es que {nombre} tenga una teoría conspirativa que defiende en serio?",
            "¿Qué tan probable es que {nombre} llegue primero a ayudarte si lo necesitas a las 3 AM?",
            "¿Qué tan probable es que {nombre} gane 'quién quiere ser millonario' sin usar comodines?",
            "¿Qué tan probable es que {nombre} se equivoque de nombre en un momento importante?",
            "¿Qué tan probable es que {nombre} haya espiado el teléfono de una pareja?",
            "¿Qué tan probable es que {nombre} se vuelva vegetariano/a después de conocer a la vaca?",
            "¿Qué tan probable es que {nombre} cante en la ducha con coreografía incluida?",
            "¿Qué tan probable es que {nombre} sea multado/a por quedarse dormido/a en el metro?",
            "¿Qué tan probable es que {nombre} defienda con su vida una comida que a todos les parece mala?",
            "¿Qué tan probable es que {nombre} tenga guardada ropa de hace 10 años 'por si vuelve a la moda'?",
            "¿Qué tan probable es que {nombre} sea el/la que propone este juego en todas las juntas desde hoy?",
            "¿Qué tan probable es que {nombre} le deba una devolución de plata a alguien de esta mesa?",
            "¿Qué tan probable es que {nombre} termine llorando de risa antes de que termine esta partida?",
        ],
    },
    "hipoteticos": {
        "nombre": "🎲 Califícalo",
        "pregunta": "¿Qué nota le pones?",
        "label_min": "Horrible",
        "label_max": "Me encanta",
        "items": [
            "Tatuarse el nombre de la pareja al mes de estar juntos.",
            "Un asado donde solo hay ensaladas.",
            "Vivir sin internet un mes a cambio de un sueldo extra.",
            "Que tu jefe te siga en Instagram.",
            "Casarse en Las Vegas con traje de Elvis.",
            "Comer lo mismo todos los días por un año, pero gratis.",
            "Saber la fecha exacta de tu muerte.",
            "Poder leer mentes, pero solo de gente aburrida.",
            "Un viaje sorpresa donde no sabes el destino hasta llegar al aeropuerto.",
            "Que tu mamá tenga acceso a tu historial de búsqueda.",
            "Volver a tener 15 años sabiendo lo que sabes ahora.",
            "Una cita a ciegas organizada por tu abuela.",
            "Karaoke obligatorio en la oficina todos los viernes.",
            "Ganar la lotería pero tener que contárselo a toda tu familia.",
            "Un mundo sin lunes, pero los sábados duran 12 horas.",
            "Dormir 4 horas y rendir como si hubieras dormido 8.",
            "Que tu mascota pueda hablar, pero solo para criticarte.",
            "Vivir en la playa pero sin señal de celular.",
            "Un botón que hace desaparecer a la gente pesada (temporalmente).",
            "Pizza con chocolate.",
            "Que tu suegra viva en el departamento de al lado.",
            "Cambiar de nombre a los 30 porque nunca te gustó el tuyo.",
            "Un espejo que te dice la verdad, sin filtro, cada mañana.",
            "Trabajar 4 días a la semana pero sin vacaciones nunca.",
            "Poder viajar en el tiempo pero solo a días aburridos de tu propia vida.",
            "Que en tu funeral pongan la canción que más escuchaste en Spotify.",
            "Un restorán donde el chef decide qué comes, sin opción a reclamar.",
            "Recibir una notificación cada vez que alguien habla de ti.",
            "Bailar una coreografía completa en el matrimonio de tu mejor amigo/a.",
            "Adoptar la mascota más fea del refugio.",
            "Un detector de mentiras en todas las citas románticas.",
            "Vivir un año en una isla desierta con tres personas de esta mesa.",
            "Que tu historial de Spotify sea público.",
            "Sushi de desayuno.",
            "Renunciar por WhatsApp con un sticker.",
            "Un clon tuyo que va a trabajar por ti, pero también va a tus cumpleaños.",
            "Saber exactamente qué piensa tu perro cuando te mira.",
            "Casarse con separación de bienes... de comida: cada uno compra lo suyo.",
            "Volver a dar la PSU/PAES mañana, sin estudiar.",
            "Un año sabático para dedicarte a tu hobby más inútil.",
            "Que tus papás vean todas tus historias de Instagram.",
            "Completos gratis de por vida, pero solo puedes comer completos en eventos sociales.",
            "Mudarte de país con una semana de aviso por el trabajo de tus sueños.",
            "Tener un loro que repite todo lo que dices en la casa... delante de las visitas.",
            "Un funeral con temática de fiesta de disfraces (idea del difunto).",
            "Ser famoso/a pero solo en Paraguay.",
            "Ducharse con agua fría todos los días a cambio de energía infinita.",
            "Que tu ex sea tu jefe directo desde el lunes.",
            "Un helado de palta.",
            "Poder silenciar personas en la vida real, con un botón.",
            "Vivir en una casa rodante recorriendo Chile por dos años.",
            "Que tu vida tenga música de fondo según tu estado de ánimo, audible para todos.",
            "Comerte un asado completo con cubiertos de plástico.",
            "Un tatuaje sorpresa: el tatuador elige.",
            "Enviarle tu ubicación en tiempo real a tu mamá para siempre.",
            "Ganar un viaje a Europa pero con el grupo de la oficina.",
            "Un apagón mundial de redes sociales por un mes.",
            "Que tu pareja tenga tu clave del teléfono (y tú la suya).",
            "Empanada con mayonesa.",
            "Ser invisible por un día, pero nadie te creerá después.",
            "Dormir todas las noches con calcetines mojados a cambio de no pagar arriendo.",
            "Un mayordomo gratis, pero es tu ex.",
            "Cantar el himno nacional en un estadio lleno.",
            "Que exista un ranking público de qué tan buen amigo/a eres.",
            "Cambiar tu apellido por el de tu pareja al casarte.",
            "Un mes sin carne a cambio de un viaje al sur con todo pagado.",
            "Tener la casa siempre impecable, pero con un fantasma amistoso que ordena.",
            "Piscola sin hielo.",
            "Que tu primer apodo del colegio vuelva oficialmente.",
            "Hacerte un piercing a los 60 años.",
            "Vivir sin música o vivir sin series: elegir una para siempre (califica el dilema).",
            "Un perro que ronca más fuerte que una persona.",
            "Decir siempre lo que piensas durante 24 horas, sin filtro.",
            "Comer pan amasado recién hecho todos los días, pero solo pan.",
            "Que tu boda la organice completamente tu suegra.",
            "Tener un gemelo/a que es más simpático/a que tú.",
            "Un televisor gigante en el techo del dormitorio.",
            "Pasar Año Nuevo trabajando a cambio del triple de sueldo ese mes.",
            "Que se filtre el chat del grupo de amigos... completo.",
            "Un jacuzzi en el balcón de un departamento de 40 metros cuadrados.",
            "Aprender un idioma nuevo instantáneamente, pero olvidas uno que ya sabes.",
            "Ser alcalde/sa de tu comuna por un año, sin sueldo.",
            "Té en bolsita reutilizada por tercera vez.",
            "Que tu auto hable y opine de tu forma de manejar.",
            "Un año entero sin comprar ropa.",
            "Celebrar tu cumpleaños dos veces al año, pero envejeces el doble ese día.",
            "Chocolate con ají.",
            "Que todos escuchen tus pensamientos por 10 segundos, una vez al día, hora aleatoria.",
            "Reunión familiar todos los domingos, obligatoria, por ley.",
            "Un colchón inteligente que publica cuántas horas dormiste.",
            "Ganarte un premio y que digan mal tu nombre en la premiación.",
            "Vivir arriba de una panadería: olor a pan 24/7.",
            "Que tu GPS tenga la voz de tu mamá dándote instrucciones.",
            "Arroz con palta y huevo frito como plato nacional oficial.",
            "Un botón de 'rehacer' que solo funciona para conversaciones incómodas.",
            "Fiesta de 15 años... a los 30, porque nunca la tuviste.",
            "Que llueva solo mientras duermes, todo el año.",
            "Un abono libre para todos los conciertos, pero siempre vas solo/a.",
            "Terminar este juego siendo el/la gran perdedor/a de la noche.",
            "Que la próxima junta sea en tu casa y tú cocines para todos.",
        ],
    },
}


def total_situaciones():
    return sum(len(c["items"]) for c in CATEGORIAS.values())
